---
version: "2.1"
services:
  plex:
    image: lscr.io/linuxserver/plex:1.29.2
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
      - PLEX_CLAIM= #optional
    volumes:
      - /home/zmw85/apps/plex/config:/config
      - /mnt/truenas-shares/TV:/tv
      - /mnt/truenas-shares/Movies:/movies
    restart: unless-stopped