---
version: "3"
services:
  vaultwarden:
    image: vaultwarden/server:1.26.0-alpine
    container_name: vaultwarden
    volumes:
      - /home/zmw85/apps/vaultwarden/data:/data
    ports:
      - 8081:80
    restart: unless-stopped