- hosts: masters
  become: yes
  tasks:
    - name: Initialize K8S control-plane
      shell: kubeadm init \
        --pod-network-cidr=172.16.0.0/16 \
        --cri-socket unix:///var/run/cri-dockerd.sock

    - name: Create .kube directory
      file:
        path: $HOME/.kube
        state: directory
        mode: 0755

    - name: Copy admin.conf to user kube config
      copy:
        src: /etc/kubernetes/admin.conf
        dest: /root/.kube/config
        remote_src: yes

    - name: Install Pod network
      become: yes
      shell: kubectl apply -f https://raw.githubusercontent.com/flannel-io/flannel/master/Documentation/kube-flannel.yml >> pod_network_setup.txt
      args:
        chdir: $HOME
        creates: pod_network_setup.txt

    - name: Insure "/run/flannel/" directory exist
      file:
        path: "/run/flannel"
        state: directory
        mode: '0755'

    - name: Create flannel config file
      copy:
        dest: "/run/flannel/subnet.env"
        content: |
          FLANNEL_NETWORK=10.244.0.0/16
          FLANNEL_SUBNET=10.244.0.1/24
          FLANNEL_MTU=1450
          FLANNEL_IPMASQ=true
