- hosts: k8s-masters
  become: yes
  gather_facts: false
  tasks:
    - name: Get join command
      shell: kubeadm token create --print-join-command
      register: join_command_raw

    - name: Set join command
      set_fact:
        join_command: "{{ join_command_raw.stdout_lines[0] }}"

- hosts: k8s-workers
  become: yes
  tasks:
    - name: Join cluster
      shell: "{{ hostvars['vm-ubuntu-0.home.io'].join_command }} \
        --ignore-preflight-errors all \
        --cri-socket unix:///var/run/cri-dockerd.sock"
      args:
        chdir: $HOME
